### ISSUE TITLE
Make openevolve-run a package command

### ISSUE THREAD

**Issue by DerPlayer2001** [codelion/openevolve#50]
Adding this to your `pyproject.toml`
```toml
[project.scripts]
openevolve-run = "openevolve.cli:main"
```
would make the openevolve-run command a installable command, would be helpful to use openevolve in other repos...
